### ISSUE TITLE
MFA accepts an anonymous function

### ISSUE THREAD

**Issue by amclain** [doughsay/afk#31]
An `MFA` currently accepts a tuple that is called with `apply()` to call a public function for a module. It would be nice if `pressed_mfa` and `released_mfa` could also be supplied with anonymous functions so that the logic they trigger doesn't need to be exposed in a public interface.

https://github.com/doughsay/afk/blob/f13a9fdc18fe0be544a6d6e17f02f790307a6bfa/lib/afk/keycode/mfa.ex#L27

**Comment by doughsay** [comment]
This would prevent AFK keymaps from being serialized too binary and loaded from disk. These keymaps are not meant to always be defined in code, they should be saveable and restorable from config files on disk.

**Comment by amclain** [comment]
Ah, that makes sense. This issue may be invalid then.

@vanvoljg and I thought it would have been nice to have when triggering things like this [flash animation](https://github.com/ElixirSeattle/xebow/blob/4e68be8a56173ce4fb2b8fd0f8a3de25d6bf364d/lib/xebow/keyboard.ex#L76) and keeping its functionality private in the module. However, after doing some experimentation on that code yesterday I think there may be a better way to make the flash happen that uses the current AFK MFA implementation (and the flash probably needs to be moved to application logic rather than keyboard logic, so the function would be public anyway).
